#!/usr/bin/env node

/**
 * Script to generate config.js from .env file
 * This allows us to use environment variables instead of hardcoding API keys
 */

const fs = require('fs');
const path = require('path');

// Load environment variables from .env file or process.env
function loadEnvFile() {
  const envVars = {};
  
  // First, check if environment variables are set in process.env (for deployment platforms)
  if (process.env.OPENWEATHER_API_KEY && process.env.GOOGLE_MAPS_API_KEY) {
    console.log('📦 Using environment variables from process.env');
    return {
      OPENWEATHER_API_KEY: process.env.OPENWEATHER_API_KEY,
      GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY
    };
  }

  // Otherwise, try to load from .env file (for local development)
  const envPath = path.join(__dirname, '.env');
  
  if (!fs.existsSync(envPath)) {
    console.error('❌ Error: .env file not found and environment variables not set!');
    console.log('📝 Please either:');
    console.log('   1. Copy .env.example to .env and fill in your API keys, OR');
    console.log('   2. Set OPENWEATHER_API_KEY and GOOGLE_MAPS_API_KEY as environment variables');
    process.exit(1);
  }

  console.log('📄 Loading environment variables from .env file');
  const envContent = fs.readFileSync(envPath, 'utf8');

  envContent.split('\n').forEach(line => {
    line = line.trim();
    // Skip empty lines and comments
    if (line && !line.startsWith('#')) {
      const [key, ...valueParts] = line.split('=');
      if (key && valueParts.length > 0) {
        envVars[key.trim()] = valueParts.join('=').trim();
      }
    }
  });

  return envVars;
}

// Generate config.js file
function generateConfig() {
  const envVars = loadEnvFile();

  // Validate required environment variables
  const requiredVars = ['OPENWEATHER_API_KEY', 'GOOGLE_MAPS_API_KEY'];
  const missingVars = requiredVars.filter(varName => !envVars[varName] || envVars[varName].includes('your_') || envVars[varName].includes('here'));

  if (missingVars.length > 0) {
    console.error('❌ Error: Missing or invalid environment variables:');
    missingVars.forEach(varName => {
      console.error(`   - ${varName}`);
    });
    console.log('\n📝 Please update your .env file with valid API keys.');
    process.exit(1);
  }

  // Generate config.js content
  const configContent = `// Auto-generated from .env file - DO NOT EDIT MANUALLY
// This file is generated by running: npm run generate-config
// To update, edit .env and run the script again

const CONFIG = {
    OPENWEATHER_API_KEY: '${envVars.OPENWEATHER_API_KEY}',
    GOOGLE_MAPS_API_KEY: '${envVars.GOOGLE_MAPS_API_KEY}'
};

// For vanilla JavaScript, we'll expose this globally
if (typeof window !== 'undefined') {
    window.CONFIG = CONFIG;
}

// For Node.js environments (testing, etc.)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = CONFIG;
}
`;

  // Write config.js
  const configPath = path.join(__dirname, 'config.js');
  fs.writeFileSync(configPath, configContent, 'utf8');

  console.log('✅ Successfully generated config.js from .env file!');
  console.log('🔑 API keys loaded:');
  console.log(`   - OPENWEATHER_API_KEY: ${envVars.OPENWEATHER_API_KEY.substring(0, 10)}...`);
  console.log(`   - GOOGLE_MAPS_API_KEY: ${envVars.GOOGLE_MAPS_API_KEY.substring(0, 10)}...`);
}

// Run the script
generateConfig();

